apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eg-connector.secretName" . }}
  namespace: {{ template "eg-connector.namespace" . }}
type: Opaque
data:
  connectorToken: |
    {{ required "A value must be entered for connectorToken" .Values.connectorToken | b64enc }}