{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eg-connector.serviceAccountName" . }}
  namespace: {{ template "eg-connector.namespace" . }}
  labels:
    app: {{ template "eg-connector.name" . }}
{{ include "eg-connector.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}